### PR TITLE
Fixed More Personalities Component

### LINKED ISSUE #892: Fix More Personalities component
## Background Information
The More Personalities component should return random personalities, excluding the personality of the page we are on

### PR DESCRIPTION
**Pull request by caneppelevitor**
Closes #892

### CODE REVIEW

File: server/personality/personality.controller.ts [hunk 1]
```diff
@@ -136,19 +136,26 @@ export class PersonalityController {
             {
                 language: req.language,
                 order: "random",
-                pageSize: 6,
+                pageSize: 7,
                 fetchOnly: true,
```
Comment (pepermao) [inline server/personality/personality.controller.ts:140]: Suggestion: I would try another way, adding a filter to the query object

```js
_id: { $ne: personality?._id },
```

and in the `personality.service`

```js
verifyInputsQuery(query) {
        const queryInputs: any = {};
        if (query.name) {
            queryInputs.name = { $regex: query.name, $options: "i" };
        }
        if(query._id) {
            queryInputs._id = query._id
        }
        return queryInputs;
    }
```

**Review by thesocialdev — APPROVED** [review]

**Comment by thesocialdev** [comment]
chore: @caneppelevitor this needs rebase now.

File: server/personality/personality.controller.ts [hunk 2]
```diff
@@ -162,23 +162,18 @@ export class PersonalityController {
                 order: "random",
                 pageSize: 6,
                 fetchOnly: true,
+                filter: personality._id,
             }
         );
 
-        hideDescriptions[TargetModel.Personality] =
```
Comment (thesocialdev) [inline server/personality/personality.controller.ts:168]: question: is this intended? should this be removed?

**Review by thesocialdev — APPROVED** [review]
