### PR TITLE
Fixed creating two different personalities at once

### LINKED ISSUE #891: BUG: Creating two different personalities at once
## Background Information
It's possible to create more than one personality at once by quickly clicking on the add personality buttons.

## What
Disable all add personality buttons after creating one.

### PR DESCRIPTION
**Pull request by pepermao**
Avoid create more than one personality at once by quickly clicking on the add personality buttons.

closes #891

### CODE REVIEW

File: src/components/Personality/PersonalityCreateSearch.tsx [hunk 1]
```diff
@@ -28,14 +28,16 @@ const PersonalityCreateSearch = ({
...
-        const createClaim = () => {
+        const createClaim = async () => {
             selectPersonality(newPersonality);
             setIsFormSubmitted(false);
         };
 
         // Redirect to personality list in case _id is not present
         const path = slug ? `/personality/${slug}` : "/personality";
-        selectPersonality !== null ? createClaim() : router.push(path);
+        selectPersonality !== null
```
Comment (thesocialdev) [inline src/components/Personality/PersonalityCreateSearch.tsx:38]: **suggestion:** in this case is better to use an if statement, the ternary operator is hard to read and not suitable if you're not assigning a value to a variable.

**Review by thesocialdev — CHANGES_REQUESTED** [review]

**Review by thesocialdev — APPROVED** [review]
