### PR TITLE
i18n server and client side #54

### LINKED ISSUE #54: i18n server and client side

### LINKED ISSUE #454: Pop-up messages when login succeeds or fails
## Background Information
 When trying to login it doesn't show any message if the user succeeds or fails

### LINKED ISSUE #460: Apply i18n for every API responses in the client-side

### PR DESCRIPTION
**Pull request by pepermao**
closes #460 
closes #454

### CODE REVIEW

File: src/api/ory.ts [hunk 1]
```diff
@@ -25,7 +26,11 @@ const oryGetLoginFlow = ({ router, setFlow, t }) => {
 const orySubmitLogin = ({router, flow, setFlow, t, values}) => {
     return ory
         .submitSelfServiceLoginFlow(String(flow?.id), undefined, values)
-        .then(() => {
+        .then((response) => {
+            console.log(response)
```
Comment (thesocialdev) [inline src/api/ory.ts:30]: Remove console.log

**Review by thesocialdev — APPROVED** [review]
